### ISSUE TITLE
Change package version during the deployment

### ISSUE THREAD

**Issue by ChameleonTartu** [samuelmeuli/action-maven-publish#20]
Hi, 

Thank you for creating this awesome action. It is a lifesaver!

I want to request another feature when it is possible to change the package version during release. 

*Workflow:*

- Deploy to Maven only when there is a new release tag
- When release tag is picked it should be a higher priority than version into the Maven pom

**Comment by ChameleonTartu** [comment]
Actually, I solved this problem by adding an extra step:

```
 - if: github.event.release
        name: Update version in pom.xml (Release only)
        run: mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false
```

but I still consider this to be a good addition to the library.

**Comment by ksclarke** [comment]
Fwiw, Maven now supports dynamic (CI-friendly) versioning as of 3.5.0: https://maven.apache.org/maven-ci-friendly.html

This means on release you can do:
```
      - name: Release with Maven
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          gpg_private_key: ${{ secrets.BUILD_KEY }}
          gpg_passphrase: ${{ secrets.BUILD_PASSPHRASE }}
          nexus_username: ${{ secrets.SONATYPE_USERNAME }}
          nexus_password: ${{ secrets.SONATYPE_PASSWORD }}
          maven_profiles: "release"
          maven_args: >
            -Drevision=${{ github.event.release.tag_name }}
```
