### ISSUE TITLE
Snapshot and Release

### ISSUE THREAD

**Issue by pinonpierre** [samuelmeuli/action-maven-publish#5]
Hi,
Very good Job!

Do you have an idea for the workflow I try to put in place:
- First Github Action on develop branch that deploy snapshot versions only
- Second Github Action on master branch that deploy release versions only

For now, it deploy snapshot and release version on master and develop branches

Thanks a lot,

**Comment by pinonpierre** [comment]
I finally did that:

```
name: Deploy

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Get Version
        id: version
        run: echo ::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)

      - name: Deploy Snapshot Maven package
        if: (github.ref == 'refs/heads/develop') && endsWith(steps.version.outputs.version, '-SNAPSHOT')
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}

      - name: Deploy Release Maven package
        if: (github.ref == 'refs/heads/master') && endsWith(steps.version.outputs.version, '-SNAPSHOT') == false
        uses: samuelmeuli/action-maven-publish@v1
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
```
