### ISSUE TITLE
Error: spawnSync /bin/sh ENOENT

### ISSUE THREAD

**Issue by CollinAlpert** [samuelmeuli/action-maven-publish#8]
I have attached a screenshot of the error message. Do I need to change something in my .yml definition?
<img width="796" alt="Screen Shot 2020-01-12 at 13 34 09" src="https://user-images.githubusercontent.com/14217185/72218904-8f810d80-3540-11ea-8b4f-f564cfdda038.png">

**Comment by samuelmeuli** [comment]
Could you please share your workflow?

**Comment by CollinAlpert** [comment]
```yaml
maven_deploy:
    name: Deploy to Maven
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '13'

      - name: Release to Central Repository
        uses: samuelmeuli/action-maven-publish@v1.3.0
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}
```
